### PR TITLE
[WIP] Add olm event structs

### PR DESCRIPTION
**Pull request by christarazi**

### CODE REVIEW

**Comment by mujx** [comment]
We might need to have special events for olm & megolm.

For example here is an olm event

```
{
  "content": {
    "algorithm": "m.olm.v1.curve25519-aes-sha2",
    "ciphertext": {
      "1OaiUJ7OfIEGAtnMQyTPFi9Ou6LD5UjSZ4eMk6WzI3E": {
        "body": "AwogkcAq9+r4YNvCwvBXmipeM30ZVhVDYBWPZ.......69/rEhCK38SIILvCA5NvEH",
        "type": 0
      }
    },
    "sender_key": "TEdjuBVstvGMy0NYJxpeD7Zo97bLEgT2ukefWDPbe0w"
  },
  "sender": "@test:matrix.org",
  "type": "m.room.encrypted"
}
```

From the docs:
- The `ciphertext` is an object mapping from the Curve25519 identity key for the recipient device.
- The `sender_key` property of the event content gives the Curve25519 identity key of the sender.

**Comment by christarazi** [comment]
For 42ca2e1, I mostly just took your example from the example crypto bot. I have an integration test with mtxclient that uses it as well.

For 17b305d, I was getting a compilation error when trying to use the matrix-structs library with mtxclient, but when compiling the library alone, I didn't get any errors.

**Comment by christarazi** [comment]
Oops, forgot to rebase new changes. Will fix this.

**Comment by mujx** [comment]
Is this still a WIP or it can be merged?

**Comment by christarazi** [comment]
It still is WIP, but it can be merged as is. It's possible to keep pushing to a merged pull request, right? If not, I can just create a new one. 

I've been quite busy lately, so apologies for that. But I will continue to try to find time!

**Comment by mujx** [comment]
No worries, there is no rush. I was just checking in case this needs to be merged for mtxclient, but it's not really urgent at this point.

**Comment by christarazi** [comment]
Currently, this PR can serve as a stand-in replacement for the struct definitions in `nheko` on the `e2ee` branch, so I think this would be a good time to merge and close this. 

There's still a lot more to be done, but I'd like to get this PR out of the way and not hold it up too long, before it comes unmanageable. 

Is that alright with you, @mujx?

**Comment by mujx** [comment]
Yup it's fine by me, thanks again @christarazi !

**Pull request merged**
